### ISSUE TITLE
Add Curation Labels to DataverseNO

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#14]
The DataverseNO curation network has agreed to configure DataverseNO with the Curation Labels defined below.

To configure DataverseNO with these lables, the following command must be run (see [https://guides.dataverse.org/en/latest/installation/config.html#allowedcurationlabels](https://guides.dataverse.org/en/latest/installation/config.html#allowedcurationlabels)):

> curl -X PUT -d '{"Standard Process":["Curator Assigned", "In Curation", "Awaiting Reply", "Legal/Ethical Concerns", "Awaiting Final Approval", "In Double-Blind Review", "Awaiting Article  Publication", "Candidate for Deletion"], "Alternate Process":["State 1","State 2","State 3"]}' http://localhost:8080/api/admin/settings/:AllowedCurationLabels

Please configure these Curation Labels on test-docker.dataverse.no and demo.dataverse.no. Thanks!

**Comment by philippconzett** [comment]
@4tikhonov @Louis-wr When I try to configure Curation Labels on demo.dataverse.no, I only see two options: "Alternate Process" and "Disabled":

![image](https://user-images.githubusercontent.com/21955790/210307879-cea65d25-3414-45e3-b308-001ef403a020.png)


The main option "Standard Process" is missing. Could you please verify that the API command above was properly run? Thanks!

**Comment by Louis-wr** [comment]
fixed by removing the unhallowed special char as per https://guides.dataverse.org/en/latest/installation/config.html#allowedcurationlabels
 The curation label is now:
curl -X PUT -d '{"Standard Process":["Curator Assigned", "In Curation", "Awaiting Reply", "Legal or Ethical Concerns", "Awaiting Final Approval", "In Double Blind Review", "Awaiting Article Publication", "Candidate for Deletion"], "Alternate Process":["State 1","State 2","State 3"]}' http://localhost:8080/api/admin/settings/:AllowedCurationLabels
